name: Build and Deploy Node Aplication

on:
  workflow_dispatch: {}

env:
  APPLICATION_FOLDER: /nodeservice
  APP_NAME: Node Microservice
  DEPLOYMENT_GROUP: ${{ vars.DEPLOYMENT_GROUP }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  APP_PORT: ${{ vars.APP_PORT }}
  S3_BUCKET: ${{ vars.S3_BUCKET }}

jobs:
  build:
    name: Install dependencies and build application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Compress artifact
        run: tar -czvf * app.tar.gz

      - name: Upload Artifact to s3
        working-directory: ${{ env.APPLICATION_FOLDER }}
        run: aws s3 cp * s3://${{ env.S3_BUCKET }}/
  
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
        role-session-name: 'GitHub-Action-Role'
        aws-region: ${{ env.AWS_REGION }}
    - run: |
        aws deploy create-deployment \
          --application-name ${{ env.APP_NAME }} \
          --deployment-group-name ${{ env.DEPLOYMENT_GROUP }} \
          --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash \
          --ignore-application-stop-failures